version: '3.8'

services:
  admin:
    build:
      context: ./admin
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    networks:
      - app-network

  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "3002:3000"
    networks:
      - app-network

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    networks:
      - app-network

  mysql-server:
    image: mysql:latest
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: blog-db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
